package it.mbc.hft.common.rem.enums;

public enum GuardOperator {
    GTE,
    LTE,
    BETWEEN,
    FEATURE_GTE,
    FEATURE_LTE,
    FEATURE_BETWEEN,
    PRESENT,
    FRESH_WITHIN_SECONDS,
    ECONOMIC_FEASIBLE,
    PROFIT_FLOOR_AFTER_ARM_EXIT,
    DYNAMIC_TRAILING_EXIT,
    MICRO_PROFIT_TAKE_EXIT,
    ABSOLUTE_LOSS_EXIT,
    COST_AWARE_QUOTE_LOSS_CAP_EXIT,
    QUOTE_LOSS_CAP_EXIT,
    FEE_RANGE_MAX_HOLD_EXIT,
    ML_ADVICE_TAKE_PROFIT_EXIT,
    ML_ADVICE_DYNAMIC_TRAILING_EXIT,
    ML_ADVICE_NO_MFE_DECAY_EXIT,
    ML_ADVICE_POSITIVE_DURATION_EXIT,
    ML_ADVICE_LOSS_CAP_EXIT,
    ML_ADVICE_TIMEOUT_EXIT
}
